Missing test dependencies
`make clean && make CppunitTest_sw_xhtmlexport` SIGABRT'ed with

[...]
> warn:vcl.builder:649768:649768:vcl/source/window/builder.cxx:462: DBG_UNHANDLED_EXCEPTION in VclBuilder::VclBuilder(vcl::Window *, const rtl::OUString &, const rtl::OUString &, const rtl::OString &, const css::uno::Reference<css::frame::XFrame> &, bool, const NotebookBarAddonsItem *)
>     when: Unable to read .ui file exception: com.sun.star.container.NoSuchElementException message: file:///.../instdir/share/config/soffice.cfg/svx/ui/sidebarstylespanel.ui
> warn:sfx.sidebar:649768:649768:sfx2/source/sidebar/SidebarController.cxx:976: Cannot create panel private:resource/toolpanel/SvxPanelFactory/StylesPropertyPanel com.sun.star.container.NoSuchElementException message: file:///.../instdir/share/config/soffice.cfg/svx/ui/sidebarstylespanel.ui
> warn:vcl.builder:649768:649768:vcl/source/window/builder.cxx:462: DBG_UNHANDLED_EXCEPTION in VclBuilder::VclBuilder(vcl::Window *, const rtl::OUString &, const rtl::OUString &, const rtl::OString &, const css::uno::Reference<css::frame::XFrame> &, bool, const NotebookBarAddonsItem *)
>     when: Unable to read .ui file exception: com.sun.star.container.NoSuchElementException message: file:///.../instdir/share/config/soffice.cfg/svx/ui/sidebartextpanel.ui
> warn:sfx.sidebar:649768:649768:sfx2/source/sidebar/SidebarController.cxx:976: Cannot create panel private:resource/toolpanel/SvxPanelFactory/TextPropertyPanel com.sun.star.container.NoSuchElementException message: file:///.../instdir/share/config/soffice.cfg/svx/ui/sidebartextpanel.ui
> warn:vcl.builder:649768:649768:vcl/source/window/builder.cxx:462: DBG_UNHANDLED_EXCEPTION in VclBuilder::VclBuilder(vcl::Window *, const rtl::OUString &, const rtl::OUString &, const rtl::OString &, const css::uno::Reference<css::frame::XFrame> &, bool, const NotebookBarAddonsItem *)
>     when: Unable to read .ui file exception: com.sun.star.container.NoSuchElementException message: file:///.../instdir/share/config/soffice.cfg/svx/ui/sidebarparagraph.ui
> warn:legacy.osl:649768:649768:vcl/source/window/window.cxx:269: Window ( 7Control()) with live children destroyed:  7VclVBox()
> Window ( 7Control()) with live children destroyed:  7VclVBox()

and then still failed with

[...]
> I/O warning : failed to load external entity "file:///.../instdir/share/xslt/export/xhtml/opendoc2xhtml.xsl"
> error
> xsltParseStylesheetFile : cannot parse file:///.../instdir/share/xslt/export/xhtml/opendoc2xhtml.xsl
> warn:filter.xslt:662169:662186:filter/source/xsltfilter/XSLTFilter.cxx:234: XSLTFilter::error was called: com.sun.star.uno.Exception message: failed to load external entity "file:///.../instdir/share/xslt/export/xhtml/opendoc2xhtml.xsl"
>
> warn:xmloff:662169:662169:xmloff/source/core/xmlerror.cxx:169: An error or a warning has occurred during XML import/export!
> Error-Id: 0x60040004
>     Flags: 6 ERROR SEVERE
>     Class: 4 API
>     Number: 4
> Parameters:
> Exception-Message: com.sun.star.uno.RuntimeException: ""
>
> warn:sfx.doc:662169:662169:sfx2/source/doc/sfxbasemodel.cxx:3096: Storing has failed, no error is set!
> image-mimetype.odt:
> unknown:0:testImageEmbedding::Import_Export
> An uncaught exception of type com.sun.star.io.IOException
> - SfxBaseModel::impl_store <file:///TMPDIR/libtest_sw_xhtmlexport.sozwb87q.tmp> failed: 0xc10(Error Area:Io Class:Write Code:16)

and then still failed with

[...]
> I/O warning : failed to load external entity "file:///.../instdir/share/xslt/export/common/styles/style_collector.xsl"
> compilation error: file file:///.../instdir/share/xslt/export/xhtml/opendoc2xhtml.xsl line 55 element include
> xsl:include : unable to load file:///.../instdir/share/xslt/export/common/styles/style_collector.xsl
> I/O warning : failed to load external entity "file:///.../instdir/share/xslt/export/common/styles/style_mapping_css.xsl"
> compilation error: file file:///.../instdir/share/xslt/export/xhtml/opendoc2xhtml.xsl line 58 element include
> xsl:include : unable to load file:///.../instdir/share/xslt/export/common/styles/style_mapping_css.xsl
> I/O warning : failed to load external entity "file:///.../instdir/share/xslt/common/measure_conversion.xsl"
> compilation error: file file:///.../instdir/share/xslt/export/xhtml/body.xsl line 28 element import
> xsl:import : unable to load file:///.../instdir/share/xslt/common/measure_conversion.xsl
> I/O warning : failed to load external entity "file:///.../instdir/share/xslt/export/common/body.xsl"
> compilation error: file file:///.../instdir/share/xslt/export/xhtml/body.xsl line 31 element import
> xsl:import : unable to load file:///.../instdir/share/xslt/export/common/body.xsl
> I/O warning : failed to load external entity "file:///.../instdir/share/xslt/export/common/table/table.xsl"
> compilation error: file file:///.../instdir/share/xslt/export/xhtml/body.xsl line 34 element import
> xsl:import : unable to load file:///.../instdir/share/xslt/export/common/table/table.xsl
> warn:filter.xslt:662890:662907:filter/source/xsltfilter/XSLTFilter.cxx:234: XSLTFilter::error was called: com.sun.star.uno.Exception message: failed to load external entity "file:///.../instdir/share/xslt/export/common/table/table.xsl"
>
> warn:xmloff:662890:662890:xmloff/source/core/xmlerror.cxx:169: An error or a warning has occurred during XML import/export!
> Error-Id: 0x60040004
>     Flags: 6 ERROR SEVERE
>     Class: 4 API
>     Number: 4
> Parameters:
> Exception-Message: com.sun.star.uno.RuntimeException: ""
>
> warn:sfx.doc:662890:662890:sfx2/source/doc/sfxbasemodel.cxx:3096: Storing has failed, no error is set!
> image-mimetype.odt:
> unknown:0:testImageEmbedding::Import_Export
> An uncaught exception of type com.sun.star.io.IOException
> - SfxBaseModel::impl_store <file:///TMPDIR/libtest_sw_xhtmlexport.sozwmx0q.tmp> failed: 0xc10(Error Area:Io Class:Write Code:16)

Change-Id: I295222448be208582003c62e3d610f6fe743af3d
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/90772
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>
(cherry picked from commit f7efe5a7fe8ade48fe376eb817017b26892f95b3)
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/90813